src/content/github/pr/constants.ts, src/content/github/pr/main.tsx
update PR line annotation logic to support logged out view
=> update PR line annotation logic

src/background/main.ts, src/content/github/file/constants.ts, src/content/github/file/main.tsx, src/content/github/file/utils/constants.ts, src/content/github/file/utils/dropdown.tsx, src/content/github/file/utils/fetchers.ts, src/content/github/pr/main.tsx, src/utils.ts
used common function to create both flags and components dropdown, split code into multiple files
=> Refactor file view content script

src/content/github/file/main.tsx, src/content/github/file/utils/fetchers.ts, src/content/github/pr/main.tsx
=> PR unified view: don't attempt to annotate deleted lines

public/manifest.firefox.json, public/manifest.json, src/background/dynamic_content_scripts.ts, src/popup/main.tsx
=> Fix self hosted provider support

src/content/github/common/fetchers.ts, src/content/github/file/main.tsx, src/types.ts, src/utils.ts
=> Use commit hashes only

README.md
Link to extension page and some stats - version, users, rating
=> Add web store badges

src/content/github/pr/main.tsx
=> use box shadow for PR annotations

src/content/github/common/fetchers.ts, src/content/github/file/main.tsx, src/types.ts
=> show prompt for past commit report

.github/workflows/ci.yml, package-lock.json, package.json, src/content/common/sentry.ts, src/content/github/file/main.tsx, src/content/github/pr/main.tsx, webpack/webpack.common.js, webpack/webpack.prod.js
Add Sentry error monitoring to GitHub injection code for detecting breaking changes coming down from GitHub.
Environment variables to be added to CD pipeline.
=> feat: Add Sentry error monitoring

README.md
Update README with info about setting up the Safari extension.
=> Update README.md with Safari instructions

package-lock.json, package.json
Updates the sentry browser js sdk
=> Update sentry sdk

src/background/main.ts, src/content/common/sentry.ts, src/content/github/file/main.tsx, webpack/webpack.common.js
Reverts codecov/codecov-browser-extension#91 as it caused a regression.
=> Revert "Add sentry tracing to network requests"

src/background/main.ts, webpack/webpack.common.js
Turns out I was not returning the resulting promise. I actually tested everything properly this time as well and it is working.
=> Add sentry tracing attempt two

src/content/github/file/main.tsx, src/content/github/pr/main.tsx
Was helping out with the static analysis training and the LLM suggested these fixes lol. LGTM
=> fix: Couple of Sentry errors using suggestions from static analysis

package-lock.json, package.json
Reverts codecov/codecov-browser-extension#104
I did my testing wrong, stuff is actually broken.
=> Revert "Bump the npm_and_yarn group with 3 updates"

package-lock.json, package.json
Upgrades postcss to 8.4.49. Tested on FF and Chrome all is working.
Closes https://github.com/codecov/internal-issues/issues/1103
=> chore: Upgrade postcss to 8.4.49

src/content/github/file/main.tsx, src/content/github/file/utils/dropdown.tsx
This PR fixes the currently (totally) broken flags and components dropdowns. It seems GH made a change to the dom here recently and it broke our manipulations. With the fix I've also just simplified the process a good bit.
=> fix: Flags and components dropdowns

.github/workflows/ci.yml, .github/workflows/publish.yml, package-lock.json, package.json, webpack/webpack.prod.js
Adds a new ci.yml workflow to build and upload bundle stats to Codecov. Renames old ci.yml to publish.yml.
=> feat: Add Bundle analysis

package-lock.json
Updates braces to 3.0.3 to resolve a vuln.
Closes https://github.com/codecov/internal-issues/issues/1280
=> chore: Update braces to 3.0.3

.github/workflows/ci.yml, .github/workflows/publish.yml, .gitignore, README.md, package-lock.json, package.json, public/manifest.firefox.json, public/manifest.json, webpack/webpack.common.js
Should help to resolve https://github.com/codecov/engineering-team/issues/3536 and #124 once a new release is cut.
=> build: Fix and improve builds for Mozilla Firefox requirements

src/content/github/pr/main.tsx
Found while testing latest changes more thoroughly on main.
=> fix: Order of operations bug in pr/main
